// Gen AI Assignment 2 | editable Typst source
// Compile from this directory with: typst compile <file>.typ <file>.pdf

#set page(
  paper: "a4",
  margin: 2.5cm,
  numbering: none,
  footer: context [
    #if counter(page).get().first() > 1 [
      #align(center)[#(counter(page).get().first() - 1)]
    ]
  ],
  header: context [
    #if counter(page).get().first() > 1 [
      #set text(font: "Times New Roman", size: 9pt)
      #align(center)[Agent & Multi-Agent Systems: Task 1 Research Report]
      #v(4pt)
      #line(length: 100%, stroke: 0.5pt)
    ]
  ],
  header-ascent: 1cm,
)
#set text(font: "Times New Roman", size: 12pt, lang: "en", tracking: 0.2pt)
#set par(first-line-indent: (amount: 1.5em, all: true), leading: 0.8em, spacing: 0.8em, justify: true)
#set figure(gap: 0.8em)
#set figure.caption(position: bottom, separator: [. ])
#show figure.where(kind: table): set figure.caption(position: top)
#show figure.caption: set text(size: 10pt)
#show figure: set block(above: 12pt, below: 20pt)
#set table(stroke: none, inset: (x: 6pt, y: 5pt), align: center)
#set heading(numbering: "1.1")
#show heading.where(level: 1): set text(weight: "bold", size: 17pt)
#show heading.where(level: 2): set text(weight: "bold", size: 13pt)
#show heading: set block(above: 16pt, below: 16pt)
#show raw.where(block: true): set text(font: "Consolas", size: 9pt)
#show raw.where(block: true): block.with(
  width: 100%,
  fill: rgb("#F6F8FA"),
  stroke: 0.5pt + rgb("#DDE3EA"),
  radius: 5pt,
  inset: 12pt,
  above: 8pt,
  below: 8pt,
)
#set list(indent: 2.5em, body-indent: 0.6em)

#align(center)[
  #v(2.4cm)
  #text(size: 17pt, weight: "bold")[Gen AI · Assignment 2]
  #v(1cm)
  #text(size: 27pt, weight: "bold")[Task 1 Research Report]
  #v(0.8cm)
  #text(size: 16pt)[Reinforcement Learning for Quadrotor Trajectory Tracking]
  #v(6.2cm)
  #table(
    columns: (6cm, 7cm),
    stroke: none,
    inset: (x: 8pt, y: 9pt),
    align: (right, left),
    [Name:], [Hanwen Hu],
    [Student ID:], [3240104699],
    [Frozen run:], [`advanced_20261003_213736`],
    [Date:], [October 3, 2026],
  )
]
#pagebreak()

= Report Note

This document is an English rendering of the final research report generated by the frozen Task 1 MAS run. The original Chinese `report.md`, `review.md`, `trace.jsonl`, and `evidence_registry.json` are preserved in the submitted frozen-output directory. No new external sources are added here; the `[S#]` identifiers below refer only to that run's evidence registry.

= Problem Definition

This small technical survey is written for undergraduate readers and focuses on the application of reinforcement learning to quadrotor trajectory tracking. The intended research goals are: first, to identify the basic frameworks and major algorithm categories used for reinforcement-learning-based quadrotor trajectory tracking; second, to compare reinforcement-learning approaches with traditional controllers such as PID and model predictive control (MPC); and third, to summarize representative applications and practical deployment challenges.

= Main Findings

Based on the retrieved evidence, only the following statements can be confirmed. The four items returned from the course database all concern LLM-based multi-agent systems: a multi-agent software-development framework, an agent system for PLC code generation and verification, a multi-agent conversation framework, and a survey of LLM-based MASs [S1][S2][S3][S4]. They are unrelated to the target topic and therefore cannot support technical claims about quadrotor trajectory tracking.

Crossref returned four topic-relevant academic records. From the titles, the records concern reinforcement-learning-based anti-interference trajectory tracking [S5], a composite MPC-INDI framework for quadrotor trajectory tracking [S6], off-policy reinforcement learning for optimal quadrotor trajectory tracking [S7], and deep reinforcement learning for quadrotor trajectory control in virtual environments [S8]. However, Crossref did not provide abstracts or core technical content for any of these four records. Only bibliographic information such as title, author, year, and DOI was available, so no method details or experimental conclusions can be extracted safely.

= Comparison

Because the retrieved records do not contain experimental data, controller parameters, or performance metrics, the available evidence does not support either a quantitative or qualitative comparison between reinforcement-learning approaches and traditional control approaches in terms of tracking accuracy, disturbance rejection, computational complexity, or application boundaries.

= Limitations

The central limitation of this survey is insufficient usable evidence. The course-database results are off-topic, while the topic-relevant Crossref records contain only bibliographic metadata. In addition, only four relevant records were retrieved, which is not enough to support a systematic taxonomy or a broad characterization of the research field.

= Conclusion

The retrieved evidence is insufficient for a complete technical survey. Abstracts or full texts of the topic-relevant publications, together with a broader evidence base, are required before a defensible method taxonomy, performance comparison, or application-challenge analysis can be produced.

= Evidence Registry

#figure(
  table(
    columns: (0.9cm, 2.4cm, 7.2cm, 3.3cm),
    [*ID*], [*Source*], [*Title*], [*Evidence available*],
    [S1], [Course DB], [MetaGPT: Meta Programming for A Multi-Agent Collaborative Framework], [Course summary; off-topic],
    [S2], [Course DB], [Agents4PLC: Automating Closed-loop PLC Code Generation and Verification], [Course summary; off-topic],
    [S3], [Course DB], [AutoGen: Enabling Next-Gen LLM Applications via Multi-Agent Conversation], [Course summary; off-topic],
    [S4], [Course DB], [A survey on LLM-based multi-agent systems], [Course summary; off-topic],
    [S5], [Crossref], [Anti-interference trajectory tracking control of quadrotor UAV based on reinforcement learning], [Bibliographic metadata only],
    [S6], [Crossref], [A Composite MPC-INDI Control Framework for Quadrotor Trajectory Tracking], [Bibliographic metadata only],
    [S7], [Crossref], [Optimal Trajectory Tracking Control for a Quadrotor UAV Based on Off-Policy Reinforcement Learning], [Bibliographic metadata only],
    [S8], [Crossref], [DEEP REINFORCEMENT LEARNING FOR QUADROTOR TRAJECTORY CONTROL IN VIRTUAL ENVIRONMENTS], [Bibliographic metadata only],
  ),
  caption: [Evidence available to the frozen Task 1 MAS run.],
  supplement: [Table],
)

= Final Review

The frozen Task 1 reviewer returned `REVIEW_APPROVED`. The subsequent deterministic post-hoc citation audit also reported that all eight citation identifiers used by the report existed in the evidence registry. The final report intentionally limits itself to statements that are directly supported by the retrieved metadata.
